apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: task-app
data:
  PORT: "3000"
  KAFKA_BROKER: "kafka:9092"
  MONGO_URI: "mongodb+srv://yahiamohammedmahmoud_db_user:PtP7YfW03x6xJIYo@cluster0.zz9l4nq.mongodb.net/User-Activity"
