apiVersion: v1
kind: Service
metadata:
  name: src-node-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000 
  selector:
    app: src-node-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: src-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: src-node-app
  template:
    metadata:
      labels:
        app: src-node-app
    spec:
      containers:
      - name: src-node-app
        image: yahia5034/src-node-app:latest
        imagePullPolicy: IfNotPresent  # Important for local Minikube images
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: KAFKA_BROKER
          value: "kafka-svc:9092"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/User-Activity"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
